---
  root: true
  
  parser: '@typescript-eslint/parser'
  extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
  
  plugins:
    - '@typescript-eslint'
  
  env:
    commonjs: true
    es6: true
    node: true
    jest: true
  
  parserOptions:
    ecmaVersion: 2018
    sourceType: module

  ignorePatterns:
    - node_modules/
    - coverage
    - dist
  rules:
    indent:
      - error
      - 2
    linebreak-style:
      - error
      - unix
    quotes:
      - error
      - single
    semi:
      - error
      - always
